### ISSUE TITLE
can't create Thread: Not enough space (ThreadError)

### ISSUE THREAD

**Issue by liiight** [github-changelog-generator/github-changelog-generator#402]
I'm getting this error after executing. I am using `--token`.

```
Found 914 tags
C:/Ruby23/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.13.0/lib/github_changelog_generator/generator/generator_fetcher.rb:23:in `initialize': can't create Thread: Not enough space (ThreadError)
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.13.0/lib/github_changelog_generator/generator/generator_fetcher.rb:23:in `new'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.13.0/lib/github_changelog_generator/generator/generator_fetcher.rb:23:in `block in fetch_tags_dates'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.13.0/lib/github_changelog_generator/generator/generator_fetcher.rb:21:in `each'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.13.0/lib/github_changelog_generator/generator/generator_fetcher.rb:21:in `fetch_tags_dates'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.13.0/lib/github_changelog_generator/generator/generator_tags.rb:6:in `fetch_and_filter_tags'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.13.0/lib/github_changelog_generator/generator/generator_generation.rb:7:in `compound_changelog'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.13.0/lib/github_changelog_generator.rb:29:in `run'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/github_changelog_generator-1.13.0/bin/github_changelog_generator:4:in `<top (required)>'
        from C:/Ruby23/bin/github_changelog_generator:23:in `load'
        from C:/Ruby23/bin/github_changelog_generator:23:in `<main>'
```

**Comment by olleolleolle** [comment]
Out of memory: bringing in all these in memory took more space than you had available. On your OS, perhaps the max addressable is 4gb? Can it be that much?

**Comment by liiight** [comment]
I'm using win7 64 and have 8gb ram. Dunno how much was available when running it though, I'll mind the process monitor this time

**Comment by liiight** [comment]
Any ideas?

**Comment by olleolleolle** [comment]
One random Web search turned up Jesse Storimer's book on Threads in Ruby,
and his blog post:
http://www.jstorimer.com/blogs/workingwithcode/7970125-how-many-threads-is-too-many

**Comment by olleolleolle** [comment]
So, this code:
https://github.com/skywinder/github-changelog-generator/blob/master/lib/github_changelog_generator/generator/generator_fetcher.rb#L15
is trying to open 1 Thread _per_ tag. And you had 900+.

900 open Threads with Ruby.

@skywinder: This bit used to have logic to open 50 threads max.

https://github.com/skywinder/github-changelog-generator/commits/master/lib/github_changelog_generator/generator/generator_fetcher.rb

Concurrency is hard.
https://github.com/ruby-concurrency/concurrent-ruby is a fine toolbox to
look for shiny tools in.

**Comment by liiight** [comment]
Can I limit the number of opened tags?

**Comment by skywinder** [comment]
@olleolleolle thanks for research. Ok, I will handle it. Now pretty limit with access to pc. But I will try to resolve it asap.

@liiight you can use options: following option to limit tags:
```
        --between-tags  x,y,z        Change log will be filled only between specified tags
        --exclude-tags  x,y,z        Change log will exclude specified tags
        --exclude-tags-regex [REGEX] Apply a regular expression on tag names so that they can be excluded, for example: --exclude-tags-regex ".*+d{1,}"
        --since-tag  x               Change log will start after specified tag
        --due-tag  x                 Change log will end before specified tag
```

**Comment by skywinder** [comment]
There is no recent activity for this issue. It looks like this issue is not valid anymore since it was a lot of releases. Feel free to reopen it, if it still actual. 👍
