### ISSUE TITLE
Hang on pretty print of options in 1.15.0-rc

### ISSUE THREAD

**Issue by kujenga** [github-changelog-generator/github-changelog-generator#668]
I just tried out the latest release candidate, and it seems to hang when pretty printing the options. I run the program and it just sits there, seemingly doing nothing.

When I comment out this line, which the stacktrace points to, the program continues as expected for me: https://github.com/github-changelog-generator/github-changelog-generator/blob/72452a1315e1126f3468069ff7d4dfbcefe71ab2/lib/github_changelog_generator/options.rb#L99

This is the stacktrace pointed out when I invoke `Ctrl+C`:

```
Using these options:
^CTraceback (most recent call last):
	12: from /usr/local/bin/github_changelog_generator:23:in `<main>'
	11: from /usr/local/bin/github_changelog_generator:23:in `load'
	10: from /usr/local/lib/ruby/gems/2.5.0/gems/github_changelog_generator-1.15.0.pre.rc/bin/github_changelog_generator:5:in `<top (required)>'
	 9: from /usr/local/lib/ruby/gems/2.5.0/gems/github_changelog_generator-1.15.0.pre.rc/bin/github_changelog_generator:5:in `new'
	 8: from /usr/local/lib/ruby/gems/2.5.0/gems/github_changelog_generator-1.15.0.pre.rc/lib/github_changelog_generator.rb:28:in `initialize'
	 7: from /usr/local/lib/ruby/gems/2.5.0/gems/github_changelog_generator-1.15.0.pre.rc/lib/github_changelog_generator/parser.rb:29:in `parse_options'
	 6: from /usr/local/lib/ruby/gems/2.5.0/gems/github_changelog_generator-1.15.0.pre.rc/lib/github_changelog_generator/options.rb:99:in `print_options'
	 5: from <internal:prelude>:149:in `pp'
	 4: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/delegate.rb:85:in `method_missing'
	 3: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/delegate.rb:85:in `call'
	 2: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 1: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/delegate.rb:85:in `method_missing'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/delegate.rb:85:in `call': Interrupt
```

The version I have locally:

```
$ github_changelog_generator --version
Version: 1.15.0-rc
```

**Comment by kujenga** [comment]
This may be a duplicate of https://github.com/github-changelog-generator/github-changelog-generator/issues/663

**Comment by galaxylegand** [comment]
Please deactivated all notifications thanks

Larry w strickland
