### ISSUE TITLE
`Octokit::NotFound' error happens since 372875f7 

### ISSUE THREAD

**Issue by m-tmatma** [github-changelog-generator/github-changelog-generator#695]
`github-changelog-generator` gets the following error for our repository since 372875f7 .

```
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/octokit-4.13.0/lib/octokit/response/raise_error.rb:16:
in `on_complete': GET https://api.github.com/repos/sakura-editor/sakura/compare/c1357c0cf2b5dcee5458d2e48f2b0b3130643db9...v2.2.0.0: 
404 - No common ancestor between c1357c0cf2b5dcee5458d2e48f2b0b3130643db9 and v2.2.0.0. 
// See: https://developer.github.com/v3/repos/commits/#compare-two-commits (Octokit::NotFound)
```

# reproduction scenario

Use ruby2.4 to avoid #676.

```
git clone https://github.com/github-changelog-generator/github-changelog-generator.git
cd github-changelog-generator
set CHANGELOG_GITHUB_TOKEN=xxxxx
set PATH=C:\Ruby24-x64\bin;C:\Ruby24\bin;%PATH%
```

## OK (`372875f7~`) (60ade2ac2b33006784015752f18c2117900c265d)

```
gem uninstall -a -x github_changelog_generator
git checkout 372875f7~
gem build github_changelog_generator
gem install github_changelog_generator-1.15.0.pre.rc.gem
github_changelog_generator -u sakura-editor -p sakura %TEMP%\github-changelog-http-cache --cache-log  %TEMP%\github-changelog-logger.log
```

## NG (372875f7)

```
gem uninstall -a -x github_changelog_generator
git checkout 372875f7
gem build github_changelog_generator
gem install github_changelog_generator-1.15.0.pre.rc.gem
github_changelog_generator -u sakura-editor -p sakura %TEMP%\github-changelog-http-cache --cache-log  %TEMP%\github-changelog-logger.log
```

**Comment by m-tmatma** [comment]
@ferrarimarco 

This is not windows-specific.

It happens on ubuntu 19.10 too.



## Set GitHub Token in advance


```
export CHANGELOG_GITHUB_TOKEN=xxxxxx
```

## Install gems

```
sudo apt install -y rubygems
sudo gem install specific_install
```

## Install github-changelog-generator


```
sudo gem specific_install -l https://github.com/github-changelog-generator/github-changelog-generator.git
```


## Set up variable

```
export RUBYOPT=-EUTF-8:UTF-8
```


## Run github_changelog_generator

```
github_changelog_generator -u sakura-editor -p sakura
```

## Error log

```
Traceback (most recent call last):
        22: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:321:in `block (3 levels) in fetch_tag_shas_async'
        21: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:255:in `fetch_compare'
        20: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:397:in `check_github_response'
        19: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
        18: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
        17: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
        16: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:398:in `block in check_github_response'
        15: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:255:in `block in fetch_compare'
        14: from /var/lib/gems/2.5.0/gems/octokit-4.15.0/lib/octokit/client/commits.rb:198:in `compare'
        13: from /var/lib/gems/2.5.0/gems/octokit-4.15.0/lib/octokit/connection.rb:19:in `get'
        12: from /var/lib/gems/2.5.0/gems/octokit-4.15.0/lib/octokit/connection.rb:156:in `request'
        11: from /var/lib/gems/2.5.0/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
        10: from /var/lib/gems/2.5.0/gems/faraday-0.17.3/lib/faraday/connection.rb:138:in `get'
         9: from /var/lib/gems/2.5.0/gems/faraday-0.17.3/lib/faraday/connection.rb:387:in `run_request'
         8: from /var/lib/gems/2.5.0/gems/faraday-0.17.3/lib/faraday/rack_builder.rb:143:in `build_response'
         7: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:115:in `call'
         6: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:142:in `call!'
         5: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:195:in `process'
         4: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:290:in `fetch'
         3: from /var/lib/gems/2.5.0/gems/faraday-0.17.3/lib/faraday/response.rb:8:in `call'
         2: from /var/lib/gems/2.5.0/gems/faraday-0.17.3/lib/faraday/response.rb:61:in `on_complete'
         1: from /var/lib/gems/2.5.0/gems/faraday-0.17.3/lib/faraday/response.rb:9:in `block in call'
/var/lib/gems/2.5.0/gems/octokit-4.15.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/repos/sakura-editor/sakura/compare/c1357c0cf2b5dcee5458d2e48f2b0b3130643db9...v2.2.0.0: 404 - No common ancestor between c1357c0cf2b5dcee5458d2e48f2b0b3130643db9 and v2.2.0.0. // See: https://developer.github.com/v3/repos/commits/#compare-two-commits (Octokit::NotFound)
#<Thread:0x00007f18cdd03558@/var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:319 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        22: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:321:in `block (3 levels) in fetch_tag_shas_async'
        21: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:255:in `fetch_compare'
        20: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:397:in `check_github_response'
        19: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
        18: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
        17: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
        16: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:398:in `block in check_github_response'
        15: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:255:in `block in fetch_compare'
        14: from /var/lib/gems/2.5.0/gems/octokit-4.15.0/lib/octokit/client/commits.rb:198:in `compare'
        13: from /var/lib/gems/2.5.0/gems/octokit-4.15.0/lib/octokit/connection.rb:19:in `get'
        12: from /var/lib/gems/2.5.0/gems/octokit-4.15.0/lib/octokit/connection.rb:156:in `request'
        11: from /var/lib/gems/2.5.0/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
        10: from /var/lib/gems/2.5.0/gems/faraday-0.17.3/lib/faraday/connection.rb:138:in `get'
         9: from /var/lib/gems/2.5.0/gems/faraday-0.17.3/lib/faraday/connection.rb:387:in `run_request'
         8: from /var/lib/gems/2.5.0/gems/faraday-0.17.3/lib/faraday/rack_builder.rb:143:in `build_response'
         7: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:115:in `call'
         6: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:142:in `call!'
         5: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:195:in `process'
         4: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:290:in `fetch'
         3: from /var/lib/gems/2.5.0/gems/faraday-0.17.3/lib/faraday/response.rb:8:in `call'
         2: from /var/lib/gems/2.5.0/gems/faraday-0.17.3/lib/faraday/response.rb:61:in `on_complete'
         1: from /var/lib/gems/2.5.0/gems/faraday-0.17.3/lib/faraday/response.rb:9:in `block in call'
/var/lib/gems/2.5.0/gems/octokit-4.15.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/repos/sakura-editor/sakura/compare/c1357c0cf2b5dcee5458d2e48f2b0b3130643db9...v2.2.0.1: 404 - No common ancestor between c1357c0cf2b5dcee5458d2e48f2b0b3130643db9 and v2.2.0.1. // See: https://developer.github.com/v3/repos/commits/#compare-two-commits (Octokit::NotFound)
#<Thread:0x00007f18cdd038f0@/var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:319 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        22: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:321:in `block (3 levels) in fetch_tag_shas_async'
        21: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:255:in `fetch_compare'
        20: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:397:in `check_github_response'
        19: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
        18: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
        17: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
        16: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:398:in `block in check_github_response'
        15: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:255:in `block in fetch_compare'
        14: from /var/lib/gems/2.5.0/gems/octokit-4.15.0/lib/octokit/client/commits.rb:198:in `compare'
        13: from /var/lib/gems/2.5.0/gems/octokit-4.15.0/lib/octokit/connection.rb:19:in `get'
        12: from /var/lib/gems/2.5.0/gems/octokit-4.15.0/lib/octokit/connection.rb:156:in `request'
        11: from /var/lib/gems/2.5.0/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
        10: from /var/lib/gems/2.5.0/gems/faraday-0.17.3/lib/faraday/connection.rb:138:in `get'
         9: from /var/lib/gems/2.5.0/gems/faraday-0.17.3/lib/faraday/connection.rb:387:in `run_request'
         8: from /var/lib/gems/2.5.0/gems/faraday-0.17.3/lib/faraday/rack_builder.rb:143:in `build_response'
         7: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:115:in `call'
         6: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:142:in `call!'
         5: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:195:in `process'
         4: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:290:in `fetch'
         3: from /var/lib/gems/2.5.0/gems/faraday-0.17.3/lib/faraday/response.rb:8:in `call'
         2: from /var/lib/gems/2.5.0/gems/faraday-0.17.3/lib/faraday/response.rb:61:in `on_complete'
         1: from /var/lib/gems/2.5.0/gems/faraday-0.17.3/lib/faraday/response.rb:9:in `block in call'
/var/lib/gems/2.5.0/gems/octokit-4.15.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/repos/sakura-editor/sakura/compare/c1357c0cf2b5dcee5458d2e48f2b0b3130643db9...v2.3.2.0: 404 - No common ancestor between c1357c0cf2b5dcee5458d2e48f2b0b3130643db9 and v2.3.2.0. // See: https://developer.github.com/v3/repos/commits/#compare-two-commits (Octokit::NotFound)
#<Thread:0x00007f18cdd03670@/var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:319 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        22: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:321:in `block (3 levels) in fetch_tag_shas_async'
        21: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:255:in `fetch_compare'
        20: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:397:in `check_github_response'
        19: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
        18: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
        17: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
        16: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:398:in `block in check_github_response'
        15: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:255:in `block in fetch_compare'
        14: from /var/lib/gems/2.5.0/gems/octokit-4.15.0/lib/octokit/client/commits.rb:198:in `compare'
        13: from /var/lib/gems/2.5.0/gems/octokit-4.15.0/lib/octokit/connection.rb:19:in `get'
        12: from /var/lib/gems/2.5.0/gems/octokit-4.15.0/lib/octokit/connection.rb:156:in `request'
        11: from /var/lib/gems/2.5.0/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
        10: from /var/lib/gems/2.5.0/gems/faraday-0.17.3/lib/faraday/connection.rb:138:in `get'
         9: from /var/lib/gems/2.5.0/gems/faraday-0.17.3/lib/faraday/connection.rb:387:in `run_request'
         8: from /var/lib/gems/2.5.0/gems/faraday-0.17.3/lib/faraday/rack_builder.rb:143:in `build_response'
         7: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:115:in `call'
         6: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:142:in `call!'
         5: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:195:in `process'
         4: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:290:in `fetch'
         3: from /var/lib/gems/2.5.0/gems/faraday-0.17.3/lib/faraday/response.rb:8:in `call'
         2: from /var/lib/gems/2.5.0/gems/faraday-0.17.3/lib/faraday/response.rb:61:in `on_complete'
         1: from /var/lib/gems/2.5.0/gems/faraday-0.17.3/lib/faraday/response.rb:9:in `block in call'
/var/lib/gems/2.5.0/gems/octokit-4.15.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/repos/sakura-editor/sakura/compare/c1357c0cf2b5dcee5458d2e48f2b0b3130643db9...v2.3.0.0: 404 - No common ancestor between c1357c0cf2b5dcee5458d2e48f2b0b3130643db9 and v2.3.0.0. // See: https://developer.github.com/v3/repos/commits/#compare-two-commits (Octokit::NotFound)
#<Thread:0x00007f18cdd037b0@/var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:319 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        22: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:321:in `block (3 levels) in fetch_tag_shas_async'
        21: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:255:in `fetch_compare'
        20: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:397:in `check_github_response'
        19: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
        18: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
        17: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
        16: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:398:in `block in check_github_response'
        15: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:255:in `block in fetch_compare'
        14: from /var/lib/gems/2.5.0/gems/octokit-4.15.0/lib/octokit/client/commits.rb:198:in `compare'
        13: from /var/lib/gems/2.5.0/gems/octokit-4.15.0/lib/octokit/connection.rb:19:in `get'
        12: from /var/lib/gems/2.5.0/gems/octokit-4.15.0/lib/octokit/connection.rb:156:in `request'
        11: from /var/lib/gems/2.5.0/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
        10: from /var/lib/gems/2.5.0/gems/faraday-0.17.3/lib/faraday/connection.rb:138:in `get'
         9: from /var/lib/gems/2.5.0/gems/faraday-0.17.3/lib/faraday/connection.rb:387:in `run_request'
         8: from /var/lib/gems/2.5.0/gems/faraday-0.17.3/lib/faraday/rack_builder.rb:143:in `build_response'
         7: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:115:in `call'
         6: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:142:in `call!'
         5: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:195:in `process'
         4: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:290:in `fetch'
         3: from /var/lib/gems/2.5.0/gems/faraday-0.17.3/lib/faraday/response.rb:8:in `call'
         2: from /var/lib/gems/2.5.0/gems/faraday-0.17.3/lib/faraday/response.rb:61:in `on_complete'
         1: from /var/lib/gems/2.5.0/gems/faraday-0.17.3/lib/faraday/response.rb:9:in `block in call'
/var/lib/gems/2.5.0/gems/octokit-4.15.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/repos/sakura-editor/sakura/compare/c1357c0cf2b5dcee5458d2e48f2b0b3130643db9...v2.3.1.0: 404 - No common ancestor between c1357c0cf2b5dcee5458d2e48f2b0b3130643db9 and v2.3.1.0. // See: https://developer.github.com/v3/repos/commits/#compare-two-commits (Octokit::NotFound)
Traceback (most recent call last):
        22: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:321:in `block (3 levels) in fetch_tag_shas_async'
        21: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:255:in `fetch_compare'
        20: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:397:in `check_github_response'
        19: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
        18: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
        17: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
        16: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:398:in `block in check_github_response'
        15: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:255:in `block in fetch_compare'
        14: from /var/lib/gems/2.5.0/gems/octokit-4.15.0/lib/octokit/client/commits.rb:198:in `compare'
        13: from /var/lib/gems/2.5.0/gems/octokit-4.15.0/lib/octokit/connection.rb:19:in `get'
        12: from /var/lib/gems/2.5.0/gems/octokit-4.15.0/lib/octokit/connection.rb:156:in `request'
        11: from /var/lib/gems/2.5.0/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
        10: from /var/lib/gems/2.5.0/gems/faraday-0.17.3/lib/faraday/connection.rb:138:in `get'
         9: from /var/lib/gems/2.5.0/gems/faraday-0.17.3/lib/faraday/connection.rb:387:in `run_request'
         8: from /var/lib/gems/2.5.0/gems/faraday-0.17.3/lib/faraday/rack_builder.rb:143:in `build_response'
         7: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:115:in `call'
         6: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:142:in `call!'
         5: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:195:in `process'
         4: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:290:in `fetch'
         3: from /var/lib/gems/2.5.0/gems/faraday-0.17.3/lib/faraday/response.rb:8:in `call'
         2: from /var/lib/gems/2.5.0/gems/faraday-0.17.3/lib/faraday/response.rb:61:in `on_complete'
         1: from /var/lib/gems/2.5.0/gems/faraday-0.17.3/lib/faraday/response.rb:9:in `block in call'
/var/lib/gems/2.5.0/gems/octokit-4.15.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/repos/sakura-editor/sakura/compare/c1357c0cf2b5dcee5458d2e48f2b0b3130643db9...v2.3.2.0: 404 - No common ancestor between c1357c0cf2b5dcee5458d2e48f2b0b3130643db9 and v2.3.2.0. // See: https://developer.github.com/v3/repos/commits/#compare-two-commits (Octokit::NotFound)
```

**Comment by ferrarimarco** [comment]
Is `c1357c0cf2b5dcee5458d2e48f2b0b3130643db9` a valid commit?

If I go to https://github.com/sakura-editor/changelog-sakura/commit/c1357c0cf2b5dcee5458d2e48f2b0b3130643db9 I get a 404...

**Comment by m-tmatma** [comment]
https://github.com/sakura-editor/sakura/commits/c1357c0cf2b5dcee5458d2e48f2b0b3130643db9

This commit is included at https://github.com/sakura-editor/sakura

https://github.com/sakura-editor/changelog-sakura is the repository for creating changlog of https://github.com/sakura-editor/sakura

**Comment by skywinder** [comment]
Confirmed. Can't build as well.

I will try to check, where is a problem. I don't know, why `Gemfile.lock` is not included in the repo, now it's a bit tricky to reproduce the same state of the project.

ps. I'm also want to make step-by-step guide how to build dev version of this tool. The new version is placed in `develop` branch :  

https://github.com/github-changelog-generator/github-changelog-generator/blob/develop/CONTRIBUTING.md#running-for-development

Will keep you updated.

**Comment by skywinder** [comment]
@m-tmatma  can you kindly check the current version?

**Comment by m-tmatma** [comment]
@skywinder

I tried for master
https://ci.appveyor.com/project/sakuraeditor/changelog-sakura/builds/32427669

The error message has changed, but it still failed.

(Note: This may have nothing to do with this issue, but the target repository has an official release recently on GitHub)

`C:/Ruby25-x64/bin/github_changelog_generator: stack level too deep (SystemStackError)`

```
Using these options:
:date_format=>"%Y-%m-%d"
:output=>"CHANGELOG.md"
:base=>"HISTORY.md"
:issues=>true
:add_issues_wo_labels=>true
:add_pr_wo_labels=>true
:pulls=>true
:filter_issues_by_milestone=>true
:author=>true
:unreleased=>true
:unreleased_label=>"Unreleased"
:compare_link=>true
:exclude_labels=>["duplicate", "question", "invalid", "wontfix", "CI", "management", "refactoring", "no-changelog"]
:summary_labels=>["Release summary", "release-summary", "Summary", "summary"]
:breaking_labels=>["specification change"]
:enhancement_labels=>["enhancement", "Enhancement", "Type: Enhancement"]
:bug_labels=>["bug", "Bug", "🐛bug🦋"]
:deprecated_labels=>["deprecated", "Deprecated", "Type: Deprecated"]
:removed_labels=>["removed", "Removed", "Type: Removed"]
:security_labels=>["security", "Security", "Type: Security"]
:configure_sections=>{}
:add_sections=>{}
:issue_line_labels=>[]
:max_issues=>nil
:simple_list=>false
:ssl_ca_file=>nil
:verbose=>true
:header=>"# Changelog"
:merge_prefix=>"### その他変更"
:issue_prefix=>"**Closed issues:**"
:summary_prefix=>""
:breaking_prefix=>"### 仕様変更"
:enhancement_prefix=>"### 機能追加"
:bug_prefix=>"### バグ修正"
:deprecated_prefix=>"**Deprecated:**"
:removed_prefix=>"**Removed:**"
:security_prefix=>"**Security fixes:**"
:http_cache=>true
:require=>[]
:user=>"sakura-editor"
:project=>"sakura"
:cache_file=>"C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\github-changelog-http-cache"
:cache_log=>"C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\github-changelog-logger.log"
:token=>"No token used"
Found 12 tags
Fetching tags dates: 12/12
Sorting tags...
Received issues: 1002
Pull Request count: 776
Filtered pull requests: 300
Filtered issues: 148
C:/Ruby25-x64/bin/github_changelog_generator: stack level too deep (SystemStackError)
Fetching events for issues and PR: 448
Fetching closed dates for issues: 448/448
error run github_changelog_generator 
Command exited with code 1
```

**Comment by m-tmatma** [comment]
> (Note: This may have nothing to do with this issue, but the target repository has an official release recently on GitHub)

@skywinder
I reran for 372875f7, it didn't complete within 19 minutes.
So the situation is not the same when I had reported this issue.
https://ci.appveyor.com/project/sakuraeditor/changelog-sakura/builds/32428395

**Comment by m-tmatma** [comment]
@skywinder 
Do you have any comment?

**Comment by skywinder** [comment]
@m-tmatma hello, haven't check it yet. will need to investigate it again, how to reproduce this issue.

**Comment by m-tmatma** [comment]
@skywinder 
The situation has changed. This issue doesn’t happen, but new issue happens.

@takke registeresd https://github.com/github-changelog-generator/github-changelog-generator/issues/829 on behalf of me.

I close this issue.
