### ISSUE TITLE
TypeError: no implicit conversion of nil into Array

### ISSUE THREAD

**Issue by mcelicalderon** [github-changelog-generator/github-changelog-generator#738]
I have a really weird issue on MacOS, everything works fine in Ubuntu with the same repository, I have set the same github token.

```bash
be rake changelog --trace FUTURE_RELEASE='v0.3.0'                                                                                                                                                               master
** Invoke load_app (first_time)
** Execute load_app
** Invoke changelog (first_time)
** Execute changelog
rake aborted!... 100/100
TypeError: no implicit conversion of nil into Array
/Users/mcelicalderon/.rvm/gems/ruby-2.6.5/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/octo_fetcher.rb:100:in `concat'
/Users/mcelicalderon/.rvm/gems/ruby-2.6.5/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/octo_fetcher.rb:100:in `block in github_fetch_tags'
/Users/mcelicalderon/.rvm/gems/ruby-2.6.5/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/octo_fetcher.rb:269:in `iterate_pages'
/Users/mcelicalderon/.rvm/gems/ruby-2.6.5/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/octo_fetcher.rb:97:in `github_fetch_tags'
/Users/mcelicalderon/.rvm/gems/ruby-2.6.5/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/octo_fetcher.rb:68:in `block in get_all_tags'
/Users/mcelicalderon/.rvm/gems/ruby-2.6.5/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/octo_fetcher.rb:296:in `block in check_github_response'
/Users/mcelicalderon/.rvm/gems/ruby-2.6.5/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
/Users/mcelicalderon/.rvm/gems/ruby-2.6.5/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
/Users/mcelicalderon/.rvm/gems/ruby-2.6.5/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
/Users/mcelicalderon/.rvm/gems/ruby-2.6.5/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/octo_fetcher.rb:295:in `check_github_response'
/Users/mcelicalderon/.rvm/gems/ruby-2.6.5/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/octo_fetcher.rb:68:in `get_all_tags'
/Users/mcelicalderon/.rvm/gems/ruby-2.6.5/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/generator/generator_tags.rb:9:in `fetch_and_filter_tags'
/Users/mcelicalderon/.rvm/gems/ruby-2.6.5/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/generator/generator_generation.rb:8:in `compound_changelog'
/Users/mcelicalderon/.rvm/gems/ruby-2.6.5/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/task.rb:59:in `block in define'
/Users/mcelicalderon/.rvm/gems/ruby-2.6.5/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/Users/mcelicalderon/.rvm/gems/ruby-2.6.5/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/Users/mcelicalderon/.rvm/gems/ruby-2.6.5/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/Users/mcelicalderon/.rvm/gems/ruby-2.6.5/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/mcelicalderon/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/Users/mcelicalderon/.rvm/gems/ruby-2.6.5/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/mcelicalderon/.rvm/gems/ruby-2.6.5/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/Users/mcelicalderon/.rvm/gems/ruby-2.6.5/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/Users/mcelicalderon/.rvm/gems/ruby-2.6.5/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/mcelicalderon/.rvm/gems/ruby-2.6.5/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/Users/mcelicalderon/.rvm/gems/ruby-2.6.5/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/Users/mcelicalderon/.rvm/gems/ruby-2.6.5/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/Users/mcelicalderon/.rvm/gems/ruby-2.6.5/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/Users/mcelicalderon/.rvm/gems/ruby-2.6.5/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/Users/mcelicalderon/.rvm/gems/ruby-2.6.5/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/mcelicalderon/.rvm/gems/ruby-2.6.5/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/Users/mcelicalderon/.rvm/gems/ruby-2.6.5/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/Users/mcelicalderon/.rvm/gems/ruby-2.6.5/bin/rake:23:in `load'
/Users/mcelicalderon/.rvm/gems/ruby-2.6.5/bin/rake:23:in `<main>'
/Users/mcelicalderon/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
/Users/mcelicalderon/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => changelog
```

Repository is public, so might be easy to replicate

https://github.com/graphql-devise/graphql_devise

I have tried using the rake task `bundle exec rake changelog` and also the global command `github_changelog_generator "graphql-devise/graphql_devise"`

I can continue to generate the changelogs in in Linux so not a big deal, but I would really like to get to the root of this problem in MacOS.

Ruby version: 2.6.5

Gemfile.lock
```
PATH
  remote: .
  specs:
    graphql_devise (0.2.0)
      devise_token_auth (>= 0.1.43)
      graphql (>= 1.8)
      rails (>= 4.2)

GEM
  remote: https://rubygems.org/
  specs:
    actioncable (6.0.0)
      actionpack (= 6.0.0)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (6.0.0)
      actionpack (= 6.0.0)
      activejob (= 6.0.0)
      activerecord (= 6.0.0)
      activestorage (= 6.0.0)
      activesupport (= 6.0.0)
      mail (>= 2.7.1)
    actionmailer (6.0.0)
      actionpack (= 6.0.0)
      actionview (= 6.0.0)
      activejob (= 6.0.0)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (6.0.0)
      actionview (= 6.0.0)
      activesupport (= 6.0.0)
      rack (~> 2.0)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actiontext (6.0.0)
      actionpack (= 6.0.0)
      activerecord (= 6.0.0)
      activestorage (= 6.0.0)
      activesupport (= 6.0.0)
      nokogiri (>= 1.8.5)
    actionview (6.0.0)
      activesupport (= 6.0.0)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    activejob (6.0.0)
      activesupport (= 6.0.0)
      globalid (>= 0.3.6)
    activemodel (6.0.0)
      activesupport (= 6.0.0)
    activerecord (6.0.0)
      activemodel (= 6.0.0)
      activesupport (= 6.0.0)
    activestorage (6.0.0)
      actionpack (= 6.0.0)
      activejob (= 6.0.0)
      activerecord (= 6.0.0)
      marcel (~> 0.3.1)
    activesupport (6.0.0)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
      zeitwerk (~> 2.1, >= 2.1.8)
    addressable (2.7.0)
      public_suffix (>= 2.0.2, < 5.0)
    appraisal (2.2.0)
      bundler
      rake
      thor (>= 0.14.0)
    ast (2.4.0)
    bcrypt (3.1.13)
    builder (3.2.3)
    byebug (11.0.1)
    coderay (1.1.2)
    concurrent-ruby (1.1.5)
    crass (1.0.4)
    devise (4.7.1)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0)
      responders
      warden (~> 1.2.3)
    devise_token_auth (1.1.3)
      bcrypt (~> 3.0)
      devise (> 3.5.2, < 5)
      rails (>= 4.2.0, < 6.1)
    diff-lcs (1.3)
    erubi (1.9.0)
    factory_bot (5.1.1)
      activesupport (>= 4.2.0)
    faker (2.5.0)
      i18n (~> 1.6.0)
    faraday (0.16.2)
      multipart-post (>= 1.2, < 3)
    faraday-http-cache (2.0.0)
      faraday (~> 0.8)
    github_changelog_generator (1.14.3)
      activesupport
      faraday-http-cache
      multi_json
      octokit (~> 4.6)
      rainbow (>= 2.1)
      rake (>= 10.0)
      retriable (~> 2.1)
    globalid (0.4.2)
      activesupport (>= 4.2.0)
    graphql (1.9.12)
    i18n (1.6.0)
      concurrent-ruby (~> 1.0)
    jaro_winkler (1.5.3)
    loofah (2.3.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    marcel (0.3.3)
      mimemagic (~> 0.3.2)
    method_source (0.9.2)
    mimemagic (0.3.3)
    mini_mime (1.0.2)
    mini_portile2 (2.4.0)
    minitest (5.12.2)
    multi_json (1.13.1)
    multipart-post (2.1.1)
    nio4r (2.5.2)
    nokogiri (1.10.4)
      mini_portile2 (~> 2.4.0)
    octokit (4.14.0)
      sawyer (~> 0.8.0, >= 0.5.3)
    orm_adapter (0.5.0)
    parallel (1.17.0)
    parser (2.6.5.0)
      ast (~> 2.4.0)
    pry (0.12.2)
      coderay (~> 1.1.0)
      method_source (~> 0.9.0)
    pry-byebug (3.7.0)
      byebug (~> 11.0)
      pry (~> 0.10)
    public_suffix (4.0.1)
    rack (2.0.7)
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rails (6.0.0)
      actioncable (= 6.0.0)
      actionmailbox (= 6.0.0)
      actionmailer (= 6.0.0)
      actionpack (= 6.0.0)
      actiontext (= 6.0.0)
      actionview (= 6.0.0)
      activejob (= 6.0.0)
      activemodel (= 6.0.0)
      activerecord (= 6.0.0)
      activestorage (= 6.0.0)
      activesupport (= 6.0.0)
      bundler (>= 1.3.0)
      railties (= 6.0.0)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.2.0)
      loofah (~> 2.2, >= 2.2.2)
    railties (6.0.0)
      actionpack (= 6.0.0)
      activesupport (= 6.0.0)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.20.3, < 2.0)
    rainbow (3.0.0)
    rake (10.5.0)
    responders (3.0.0)
      actionpack (>= 5.0)
      railties (>= 5.0)
    retriable (2.1.0)
    rspec-core (3.8.2)
      rspec-support (~> 3.8.0)
    rspec-expectations (3.8.5)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.8.0)
    rspec-mocks (3.8.2)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.8.0)
    rspec-rails (3.8.2)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 3.8.0)
      rspec-expectations (~> 3.8.0)
      rspec-mocks (~> 3.8.0)
      rspec-support (~> 3.8.0)
    rspec-support (3.8.3)
    rubocop (0.68.1)
      jaro_winkler (~> 1.5.1)
      parallel (~> 1.10)
      parser (>= 2.5, != 2.5.1.1)
      rainbow (>= 2.2.2, < 4.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 1.4.0, < 1.6)
    rubocop-performance (1.3.0)
      rubocop (>= 0.68.0)
    rubocop-rspec (1.36.0)
      rubocop (>= 0.68.1)
    ruby-progressbar (1.10.1)
    sawyer (0.8.2)
      addressable (>= 2.3.5)
      faraday (> 0.8, < 2.0)
    sprockets (3.7.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.1)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    sqlite3 (1.4.1)
    thor (0.20.3)
    thread_safe (0.3.6)
    tzinfo (1.2.5)
      thread_safe (~> 0.1)
    unicode-display_width (1.5.0)
    warden (1.2.8)
      rack (>= 2.0.6)
    websocket-driver (0.7.1)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.4)
    zeitwerk (2.1.10)

PLATFORMS
  ruby

DEPENDENCIES
  appraisal
  factory_bot
  faker
  github_changelog_generator
  graphql_devise!
  pry
  pry-byebug
  rake (~> 10.0)
  rspec-rails
  rubocop (= 0.68.1)
  rubocop-performance
  rubocop-rspec
  sqlite3 (~> 1.3)

BUNDLED WITH
   2.0.2
```

Let me know if I can provide more information,
Thanks

**Comment by mcelicalderon** [comment]
I was able to pinpoint the problem to the cache that the Octokit client uses, disabling that option will make it work until [this line](https://github.com/github-changelog-generator/github-changelog-generator/blob/v1.14.3/lib/github_changelog_generator/generator/generator_generation.rb#L147) where `present?` is not defined for array, not sure why that happens if activesupport is required. 

This is the command I used

```bash
github_changelog_generator "graphql-devise/graphql_devise" --no-http-cache --future-release 'v0.3.0'
```

**Comment by alexjfisher** [comment]
@mcelicalderon Any idea why this is suddenly happening?  I've been through all dependencies and tried older versions, but no luck finding a culprit.

**Comment by mcelicalderon** [comment]
Well this was the first time I used the gem on MacOS, so I'm guessing it has something to do with the lower level system tools the http client uses for caching. Also for the `present?`  error, I think it probably worked before for me as I was running it with the rake task, so somewhere in that path it loads activesupport correctly? By the way, changing [this line](https://github.com/github-changelog-generator/github-changelog-generator/blob/v1.14.3/lib/github_changelog_generator/generator/generator_generation.rb#L147) to use `any?` instead of `present?` in your downloaded version of the source will fix the problem.

Also just realized how behind the latest release is from what there is on master. I did get the same cache error running the gem on the master branch, but I haven't try installing that globally to use as a command line tool without cache (there is no option to disable cache from the rake task).

**Comment by alexjfisher** [comment]
I'm on Ubuntu and it just stopped working a few? days ago.  At [Vox Pupuli](https://voxpupuli.org/), we use it as part of our [module release process](https://voxpupuli.org/docs/releasing_version/).  AFAIK, it's, (all versions I've tried), broken for everyone trying to use it right now.

The `--no-http-cache` option is working for me (but as you point out, that's unavailable in the rake task).  I've not yet hit the other problem you describe.

@mcelicalderon If it's still working for you in Ubuntu, can you dump all the gems and versions you're using (and ruby version)?  Perhaps I missed something in my testing.

**Comment by alexjfisher** [comment]
If it is still working on your Ubuntu box, does deleting `/tmp/github-changelog-http-cache` cause it to break?  (I found a repo it appeared to work on.  Deleting the cache broke it though)

**Comment by mcelicalderon** [comment]
I just checked that my Ubuntu setup is not affected by removing the `/tmp/github-changelog-http-cache` DIR. Here is my lockfile in Ubuntu which continues to work
```
PATH
  remote: .
  specs:
    graphql_devise (0.3.0)
      devise_token_auth (>= 0.1.43)
      graphql (>= 1.8)
      rails (>= 4.2)

GEM
  remote: https://rubygems.org/
  specs:
    actioncable (6.0.0)
      actionpack (= 6.0.0)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (6.0.0)
      actionpack (= 6.0.0)
      activejob (= 6.0.0)
      activerecord (= 6.0.0)
      activestorage (= 6.0.0)
      activesupport (= 6.0.0)
      mail (>= 2.7.1)
    actionmailer (6.0.0)
      actionpack (= 6.0.0)
      actionview (= 6.0.0)
      activejob (= 6.0.0)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (6.0.0)
      actionview (= 6.0.0)
      activesupport (= 6.0.0)
      rack (~> 2.0)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actiontext (6.0.0)
      actionpack (= 6.0.0)
      activerecord (= 6.0.0)
      activestorage (= 6.0.0)
      activesupport (= 6.0.0)
      nokogiri (>= 1.8.5)
    actionview (6.0.0)
      activesupport (= 6.0.0)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    activejob (6.0.0)
      activesupport (= 6.0.0)
      globalid (>= 0.3.6)
    activemodel (6.0.0)
      activesupport (= 6.0.0)
    activerecord (6.0.0)
      activemodel (= 6.0.0)
      activesupport (= 6.0.0)
    activestorage (6.0.0)
      actionpack (= 6.0.0)
      activejob (= 6.0.0)
      activerecord (= 6.0.0)
      marcel (~> 0.3.1)
    activesupport (6.0.0)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
      zeitwerk (~> 2.1, >= 2.1.8)
    addressable (2.7.0)
      public_suffix (>= 2.0.2, < 5.0)
    appraisal (2.2.0)
      bundler
      rake
      thor (>= 0.14.0)
    ast (2.4.0)
    bcrypt (3.1.13)
    builder (3.2.3)
    byebug (11.0.1)
    coderay (1.1.2)
    concurrent-ruby (1.1.5)
    crass (1.0.4)
    devise (4.7.1)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0)
      responders
      warden (~> 1.2.3)
    devise_token_auth (1.1.2)
      bcrypt (~> 3.0)
      devise (> 3.5.2, < 5)
      rails (>= 4.2.0, < 6.1)
    diff-lcs (1.3)
    erubi (1.8.0)
    factory_bot (5.0.2)
      activesupport (>= 4.2.0)
    faker (2.3.0)
      i18n (~> 1.6.0)
    faraday (0.15.4)
      multipart-post (>= 1.2, < 3)
    faraday-http-cache (2.0.0)
      faraday (~> 0.8)
    github_changelog_generator (1.14.3)
      activesupport
      faraday-http-cache
      multi_json
      octokit (~> 4.6)
      rainbow (>= 2.1)
      rake (>= 10.0)
      retriable (~> 2.1)
    globalid (0.4.2)
      activesupport (>= 4.2.0)
    graphql (1.9.12)
    i18n (1.6.0)
      concurrent-ruby (~> 1.0)
    jaro_winkler (1.5.3)
    loofah (2.2.3)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    marcel (0.3.3)
      mimemagic (~> 0.3.2)
    method_source (0.9.2)
    mimemagic (0.3.3)
    mini_mime (1.0.2)
    mini_portile2 (2.4.0)
    minitest (5.11.3)
    multi_json (1.13.1)
    multipart-post (2.1.1)
    nio4r (2.5.1)
    nokogiri (1.10.4)
      mini_portile2 (~> 2.4.0)
    octokit (4.14.0)
      sawyer (~> 0.8.0, >= 0.5.3)
    orm_adapter (0.5.0)
    parallel (1.17.0)
    parser (2.6.4.1)
      ast (~> 2.4.0)
    pry (0.12.2)
      coderay (~> 1.1.0)
      method_source (~> 0.9.0)
    pry-byebug (3.7.0)
      byebug (~> 11.0)
      pry (~> 0.10)
    public_suffix (4.0.1)
    rack (2.0.7)
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rails (6.0.0)
      actioncable (= 6.0.0)
      actionmailbox (= 6.0.0)
      actionmailer (= 6.0.0)
      actionpack (= 6.0.0)
      actiontext (= 6.0.0)
      actionview (= 6.0.0)
      activejob (= 6.0.0)
      activemodel (= 6.0.0)
      activerecord (= 6.0.0)
      activestorage (= 6.0.0)
      activesupport (= 6.0.0)
      bundler (>= 1.3.0)
      railties (= 6.0.0)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.2.0)
      loofah (~> 2.2, >= 2.2.2)
    railties (6.0.0)
      actionpack (= 6.0.0)
      activesupport (= 6.0.0)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.20.3, < 2.0)
    rainbow (3.0.0)
    rake (10.5.0)
    responders (3.0.0)
      actionpack (>= 5.0)
      railties (>= 5.0)
    retriable (2.1.0)
    rspec-core (3.8.2)
      rspec-support (~> 3.8.0)
    rspec-expectations (3.8.4)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.8.0)
    rspec-mocks (3.8.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.8.0)
    rspec-rails (3.8.2)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 3.8.0)
      rspec-expectations (~> 3.8.0)
      rspec-mocks (~> 3.8.0)
      rspec-support (~> 3.8.0)
    rspec-support (3.8.2)
    rubocop (0.68.1)
      jaro_winkler (~> 1.5.1)
      parallel (~> 1.10)
      parser (>= 2.5, != 2.5.1.1)
      rainbow (>= 2.2.2, < 4.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 1.4.0, < 1.6)
    rubocop-performance (1.3.0)
      rubocop (>= 0.68.0)
    rubocop-rspec (1.35.0)
      rubocop (>= 0.60.0)
    ruby-progressbar (1.10.1)
    sawyer (0.8.2)
      addressable (>= 2.3.5)
      faraday (> 0.8, < 2.0)
    sprockets (3.7.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.1)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    sqlite3 (1.4.1)
    thor (0.20.3)
    thread_safe (0.3.6)
    tzinfo (1.2.5)
      thread_safe (~> 0.1)
    unicode-display_width (1.5.0)
    warden (1.2.8)
      rack (>= 2.0.6)
    websocket-driver (0.7.1)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.4)
    zeitwerk (2.1.10)

PLATFORMS
  ruby

DEPENDENCIES
  appraisal
  factory_bot
  faker
  github_changelog_generator
  graphql_devise!
  pry
  pry-byebug
  rake (~> 10.0)
  rspec-rails
  rubocop (= 0.68.1)
  rubocop-performance
  rubocop-rspec
  sqlite3 (~> 1.3)

BUNDLED WITH
   1.17.3
```

**Comment by mcelicalderon** [comment]
I open a PR here #739 

That should work for now as a workaround to this issue when using the rake task at least as active Support is correctly loaded

**Comment by mcelicalderon** [comment]
Also `v1.15.0` looks like is about to be released (not downloadable via rubygems yet). I have installed by manually building the gem and the `ActiveSupport` problem appears to be fixed. Only the http cache problem remains on my mac. Now this command works without modifying the source of the gem on `v1.15.0`
```
github_changelog_generator --user graphql-devise --project graphql_devise --no-http-cache
```

**Comment by alexjfisher** [comment]
I'm 99% sure the issue was in Faraday.  I had tried 0.15.X and it didn't work for me.  But... that's because I didn't also clear `/tmp/github-changelog-http-cache` after downgrading and I guess 0.16.X had left dodgy content in it.
From https://github.com/lostisland/faraday/releases/tag/v0.17.0
> We apologise for the issues created by the v0.16.x release series, these were due to the Faraday team underestimating the latest changes applied to master since v0.15.4

**Comment by alexjfisher** [comment]
Having gotten it working, if I downgrade faraday to 0.16 (by pinning in the Gemfile), it still works *until* I remove the cache directory and try again.
If I remove the pin and `bundle update` to (upgrade faraday to 0.17), it *still* fails.
Until I nuke the cache dir.

No wonder I had so much trouble figuring out which gem to point my finger at... :)

**Comment by alexjfisher** [comment]
@iMacTia Thank you for the 0.17 release.  Is it worth mentioning needing to clear cache directories in the 0.17 release notes?

**Comment by mcelicalderon** [comment]
Confirming Faraday 0.17 also fixes the issue on MacOS, thanks. I'll close this issue now as it is not related to this gem. Also the new release 1.15 of this gem (still not available in rubygems) fixes the activesupport include problem.

**Comment by iMacTia** [comment]
@alexjfisher thanks for pointing that out, it's a gem-specific issue since we have no caching in Faraday, but I'll happily add it as a note to the release in case that could save some time to others 😃
