### ISSUE TITLE
404 - error Not found (Octokit::NotFound )  because github-site is being modified by program

### ISSUE THREAD

**Issue by AffiTheCreator** [github-changelog-generator/github-changelog-generator#740]
I'm trying to implement your software in a production environment that uses Gitlab was the DevOps. 
I've install github_changelog_generator via git clone and then install from terminal using the 
```
gem build github_changelog_generator.gemspec
gem install ./github_changelog_generator-1.15.0.gem
```
To run the program I´m using the following arguments

```
github_changelog_generator -u @user -p $PROJECT --github-site http://gitlab.MyDomain.com/@user/PROJECT --github-api http://gitlab.MyDomain.com/api/v4/projects/  --token TOKEN_VALUE
```
Where :
`@user` is my user 
`$PROJECT` is the name of my project 
` http://gitlab.MyDomain.com` is the gitlab domain of the company 
` http://gitlab.MyDomain.com/api/v4/projects/` is the API URL for all projects
`TOKEN_VALUE` the value of my personal token

```
Traceback (most recent call last):
	35: from /usr/local/bin/github_changelog_generator:23:in `<main>'
	34: from /usr/local/bin/github_changelog_generator:23:in `load'
	33: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/bin/github_changelog_generator:5:in `<top (required)>'
	32: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator.rb:35:in `run'
	31: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/generator/generator.rb:46:in `compound_changelog'
	30: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/generator/generator_tags.rb:10:in `fetch_and_filter_tags'
	29: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:85:in `get_all_tags'
	28: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:397:in `check_github_response'
	27: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
	26: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
	25: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
	24: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:398:in `block in check_github_response'
	23: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:85:in `block in get_all_tags'
	22: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:112:in `github_fetch_tags'
	21: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:93:in `calculate_pages'
	20: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:397:in `check_github_response'
	19: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
	18: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
	17: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
	16: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:398:in `block in check_github_response'
	15: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.0/lib/github_changelog_generator/octo_fetcher.rb:94:in `block in calculate_pages'
	14: from /var/lib/gems/2.5.0/gems/octokit-4.14.0/lib/octokit/client/repositories.rb:528:in `tags'
	13: from /var/lib/gems/2.5.0/gems/octokit-4.14.0/lib/octokit/connection.rb:84:in `paginate'
	12: from /var/lib/gems/2.5.0/gems/octokit-4.14.0/lib/octokit/connection.rb:156:in `request'
	11: from /var/lib/gems/2.5.0/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
	10: from /var/lib/gems/2.5.0/gems/faraday-0.17.0/lib/faraday/connection.rb:138:in `get'
	 9: from /var/lib/gems/2.5.0/gems/faraday-0.17.0/lib/faraday/connection.rb:387:in `run_request'
	 8: from /var/lib/gems/2.5.0/gems/faraday-0.17.0/lib/faraday/rack_builder.rb:143:in `build_response'
	 7: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:115:in `call'
	 6: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:142:in `call!'
	 5: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:195:in `process'
	 4: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:290:in `fetch'
	 3: from /var/lib/gems/2.5.0/gems/faraday-0.17.0/lib/faraday/response.rb:8:in `call'
	 2: from /var/lib/gems/2.5.0/gems/faraday-0.17.0/lib/faraday/response.rb:61:in `on_complete'
	 1: from /var/lib/gems/2.5.0/gems/faraday-0.17.0/lib/faraday/response.rb:9:in `block in call'
/var/lib/gems/2.5.0/gems/octokit-4.14.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET http://gitlab.MyDomain.com/repos/@user/PROJECT/tags?per_page=100: 404 - Error: 404 Not Found (Octokit::NotFound)

```
Noticed I´ve edited the Gitlab URL for security reasons, but the problem lies on the URL that is being used by the software ` http://gitlab.MyDomain.com/repos/@user/$PROJECT/tags?per_page=100: 404 - Error: 404 Not Found (Octokit::NotFound)` my problem is the github-site variable is modified to contain `/repos/@user/project/` and it should be the one i give it in the arguments.

This issue #367 i think might be the opposite to mine.

What can it be done to have it so that the URL being used is the one I indicated in github-site

A quick search on your repository and i might have found the root of the problem in lib/github_changelog_generator/generator/entry.rb on line 215

**Comment by AffiTheCreator** [comment]
I´ve created a fork for this project and modified the line mention above and it produced the same results
Still cannot access my API page for Gitlab , the output shows` http://gitlab.MyDomain.com/repos/@user/$PROJECT/tags?per_page=100: 404 - Error: 404 Not Found (Octokit::NotFound)`

**Comment by Bluefitdev** [comment]
I had the same issue, apparently its a wrong user for my part. Apparently the repo belongs to my org instead of my user
