### ISSUE TITLE
uninitialized constant Faraday::Error::ClientError (NameError)

### ISSUE THREAD

**Issue by ArturT** [github-changelog-generator/github-changelog-generator#741]
When I try to generate changelog for my project [KnapsackPro/knapsack-pro-cypress](https://github.com/KnapsackPro/knapsack-pro-cypress/) I get error `uninitialized constant Faraday::Error::ClientError (NameError)`.

A few days ago I tried to generate changelog for different project and I got the same error. I assumed it's temporary problem with Github but today issue still exists.

I guess request to Github failed and error can't be shown due to unrecognized faraday constant.

I use github_changelog_generator `1.14.3`.

```
 github_changelog_generator KnapsackPro/knapsack-pro-cypress

Traceback (most recent call last):
	17: from /Users/artur/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
	16: from /Users/artur/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
	15: from /Users/artur/.rvm/gems/ruby-2.6.3/bin/github_changelog_generator:23:in `<main>'
	14: from /Users/artur/.rvm/gems/ruby-2.6.3/bin/github_changelog_generator:23:in `load'
	13: from /Users/artur/.rvm/gems/ruby-2.6.3/gems/github_changelog_generator-1.14.3/bin/github_changelog_generator:4:in `<top (required)>'
	12: from /Users/artur/.rvm/gems/ruby-2.6.3/gems/github_changelog_generator-1.14.3/bin/github_changelog_generator:4:in `require_relative'
	11: from /Users/artur/.rvm/gems/ruby-2.6.3/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator.rb:4:in `<top (required)>'
	10: from /Users/artur/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 9: from /Users/artur/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /Users/artur/.rvm/gems/ruby-2.6.3/gems/octokit-4.14.0/lib/octokit.rb:4:in `<top (required)>'
	 7: from /Users/artur/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /Users/artur/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /Users/artur/.rvm/gems/ruby-2.6.3/gems/octokit-4.14.0/lib/octokit/default.rb:1:in `<top (required)>'
	 4: from /Users/artur/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /Users/artur/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /Users/artur/.rvm/gems/ruby-2.6.3/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:9:in `<top (required)>'
	 1: from /Users/artur/.rvm/gems/ruby-2.6.3/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:11:in `<module:Octokit>'
/Users/artur/.rvm/gems/ruby-2.6.3/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:14:in `<module:Middleware>': uninitialized constant Faraday::Error::ClientError (NameError)
Did you mean?  Faraday::ClientError
```

It seems I use the latest version of octokit gem `4.14.0`. There is similar issue reported for it https://github.com/octokit/octokit.rb/issues/1155

**Comment by ArturT** [comment]
I found fix. Updating to faraday 0.17.0 solved issue.

```
 gem install faraday
Fetching faraday-0.17.0.gem
Successfully installed faraday-0.17.0
Parsing documentation for faraday-0.17.0
Installing ri documentation for faraday-0.17.0
Done installing documentation for faraday after 4 seconds
1 gem installed
```
