### ISSUE TITLE
"Full Changelog" uses tags that are excluded

### ISSUE THREAD

**Issue by zoff99** [github-changelog-generator/github-changelog-generator#842]
i am using ```--exclude-tags``` but some of the exluded tags are used in the diff in "Full Changelog"

see:
https://github.com/zoff99/ToxAndroidRefImpl/blob/zoff99/dev003/CHANGELOG.md

output:
```
[Full Changelog](https://github.com/zoff99/ToxAndroidRefImpl/compare/trifajni-1.0.31...1.0.29)
```

here the tag "trifajni-1.0.31" is used, which was excluded with the option ```--exclude-tags```

and also therefore tags are used wrong:

```
## [1.0.28](https://github.com/zoff99/ToxAndroidRefImpl/tree/1.0.28) (2020-02-28)

[Full Changelog](https://github.com/zoff99/ToxAndroidRefImpl/compare/trifajni-1.0.29...1.0.28)
```

its release 1.0.28, bit the diff uses 1.0.28 as old tag

**Comment by bboe** [comment]
I am also seeing this issue.

**Comment by zoff99** [comment]
@olleolleolle in what release should this be fixed?
github_changelog_generator-1.15.2 does NOT fix this.

**Comment by olleolleolle** [comment]
@zoff99 In order to learn if the thing works for your use-case, you could attempt to use the version in the `master` branch.

Either using a Gemfile, https://stackoverflow.com/a/13750551/267348 
Or, using the specific_install gem: https://github.com/rdp/specific_install#usage

**Comment by zoff99** [comment]
i'm running it insider docker on circleCI with these commands:

https://github.com/zoff99/ToxAndroidRefImpl/blob/zoff99/generate_change_log/.circleci/config.yml

how can i install the master version there?

**Comment by olleolleolle** [comment]
In that case, perhaps you can `sudo $(which gem) install specific_install && sudo $(which gem) specific_install github-changelog-generator/github_changelog_generator`:

https://github.com/zoff99/ToxAndroidRefImpl/blob/zoff99/generate_change_log/.circleci/config.yml#L22

**Comment by zoff99** [comment]
hmm, thats now working

```
Installing from git@github.com:github-changelog-generator/github_changelog_generator.git
Cloning into '/tmp/d20210201-4632-18wkgqp'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
ERROR:  While executing gem ... (RuntimeError)
    '$ git clone git@github.com:github-changelog-generator/github_changelog_generator.git /tmp/d20210201-4632-18wkgqp' exited with an error
```

**Comment by zoff99** [comment]
ah ok now i get this error:

```
Fetching closed dates for issues: 153/153
Traceback (most recent call last):
	803: from /var/lib/gems/2.5.0/gems/async-1.28.5/lib/async/task.rb:265:in `block in make_fiber'
	802: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/generator/generator.rb:55:in `block in compound_changelog'
	801: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/generator/generator.rb:152:in `fetch_issues_and_pr'
	800: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/generator/generator_fetcher.rb:48:in `add_first_occurring_tag_to_prs'
	799: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/generator/generator_fetcher.rb:65:in `associate_tagged_prs'
	798: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:367:in `fetch_tag_shas'
	797: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:367:in `each'
	796: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:368:in `block in fetch_tag_shas'
	 ... 791 levels...
	  4: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:354:in `block in commits_in_tag'
	  3: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:353:in `commits_in_tag'
	  2: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:353:in `each'
	  1: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:354:in `block in commits_in_tag'
/var/lib/gems/2.5.0/gems/sawyer-0.8.2/lib/sawyer/resource.rb:55:in `[]': stack level too deep (SystemStackError)
```

**Comment by ameir** [comment]
@zoff99 I had some issues with the master branch as well. If I have time, I'll look at what's needed to fix. In the meantime, you can run this to get the changes:

```
git clone https://github.com/ameir/github-changelog-generator.git -b v1.15.2-fixes
cd github-changelog-generator/
gem build github_changelog_generator.gemspec 
gem install -N github_changelog_generator-1.15.2.gem
```

FWIW, this builds successfully from the `ruby:2.7` Docker image.

**Comment by zoff99** [comment]
the error i posted is not from compiling, but when i run the thing. it does not work but give this error

**Comment by zoff99** [comment]
@ameir your fix produces output again :+1:
