### ISSUE TITLE
Running on a private repository owned by an Organization

### ISSUE THREAD

**Issue by nabroyan** [github-changelog-generator/github-changelog-generator#856]
I looked into this project and it looks very promising!
I tried to use it to generate a changelog for a repo, which is private and owned by an organization. I tried a couple of approaches, but couldn't get it to work. Here is what I have tried so far:

`github_changelog_generator -u my_company -p private_repo_id -t generated_token`
`github_changelog_generator -u my_github_username -p private_repo_id -t generated_token`

I have generated a new token to be sure, that it has `repo` scope. I have also tried to use `CHANGELOG_GITHUB_TOKEN` environment variable instead of specifying it with command line option. Also, tried to use the repo name instead of ID, but every time I was getting the same error:

```
Traceback (most recent call last):
	35: from /usr/local/bin/github_changelog_generator:23:in `<main>'
	34: from /usr/local/bin/github_changelog_generator:23:in `load'
	33: from /Library/Ruby/Gems/2.6.0/gems/github_changelog_generator-1.15.2/bin/github_changelog_generator:5:in `<top (required)>'
	32: from /Library/Ruby/Gems/2.6.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator.rb:35:in `run'
	31: from /Library/Ruby/Gems/2.6.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/generator/generator.rb:46:in `compound_changelog'
	30: from /Library/Ruby/Gems/2.6.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/generator/generator_tags.rb:10:in `fetch_and_filter_tags'
	29: from /Library/Ruby/Gems/2.6.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:85:in `get_all_tags'
	28: from /Library/Ruby/Gems/2.6.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:399:in `check_github_response'
	27: from /Library/Ruby/Gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
	26: from /Library/Ruby/Gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
	25: from /Library/Ruby/Gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
	24: from /Library/Ruby/Gems/2.6.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:400:in `block in check_github_response'
	23: from /Library/Ruby/Gems/2.6.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:85:in `block in get_all_tags'
	22: from /Library/Ruby/Gems/2.6.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:112:in `github_fetch_tags'
	21: from /Library/Ruby/Gems/2.6.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:93:in `calculate_pages'
	20: from /Library/Ruby/Gems/2.6.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:399:in `check_github_response'
	19: from /Library/Ruby/Gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
	18: from /Library/Ruby/Gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
	17: from /Library/Ruby/Gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
	16: from /Library/Ruby/Gems/2.6.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:400:in `block in check_github_response'
	15: from /Library/Ruby/Gems/2.6.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:94:in `block in calculate_pages'
	14: from /Library/Ruby/Gems/2.6.0/gems/octokit-4.18.0/lib/octokit/client/repositories.rb:552:in `tags'
	13: from /Library/Ruby/Gems/2.6.0/gems/octokit-4.18.0/lib/octokit/connection.rb:84:in `paginate'
	12: from /Library/Ruby/Gems/2.6.0/gems/octokit-4.18.0/lib/octokit/connection.rb:156:in `request'
	11: from /Library/Ruby/Gems/2.6.0/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
	10: from /Library/Ruby/Gems/2.6.0/gems/faraday-1.0.1/lib/faraday/connection.rb:198:in `get'
	 9: from /Library/Ruby/Gems/2.6.0/gems/faraday-1.0.1/lib/faraday/connection.rb:492:in `run_request'
	 8: from /Library/Ruby/Gems/2.6.0/gems/faraday-1.0.1/lib/faraday/rack_builder.rb:153:in `build_response'
	 7: from /Library/Ruby/Gems/2.6.0/gems/faraday-http-cache-2.2.0/lib/faraday/http_cache.rb:115:in `call'
	 6: from /Library/Ruby/Gems/2.6.0/gems/faraday-http-cache-2.2.0/lib/faraday/http_cache.rb:135:in `call!'
	 5: from /Library/Ruby/Gems/2.6.0/gems/faraday-http-cache-2.2.0/lib/faraday/http_cache.rb:187:in `process'
	 4: from /Library/Ruby/Gems/2.6.0/gems/faraday-http-cache-2.2.0/lib/faraday/http_cache.rb:283:in `fetch'
	 3: from /Library/Ruby/Gems/2.6.0/gems/faraday-1.0.1/lib/faraday/response.rb:11:in `call'
	 2: from /Library/Ruby/Gems/2.6.0/gems/faraday-1.0.1/lib/faraday/response.rb:65:in `on_complete'
	 1: from /Library/Ruby/Gems/2.6.0/gems/faraday-1.0.1/lib/faraday/response.rb:12:in `block in call'
/Library/Ruby/Gems/2.6.0/gems/octokit-4.18.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/repos/my_company/private_repo_id/tags?per_page=100: 404 - Not Found // See: https://developer.github.com/v3/repos/#list-tags (Octokit::NotFound)
```
It seems that script cannot find the repo or its tags. Could you please advise on this?

**Comment by nmncllnk** [comment]
The repo you're trying to generate a changelog from, can other people inside your organization access it? (Go to your repository in GitHub, then *Settings*, then *Manage access*)?

I suspect that if at least 2 users have access, `github_changelog_generator` should work.

**Comment by nabroyan** [comment]
Yes, its our dev repo and more than 10 developers work on that repo.
However I do not have permission of viewing _Settings_ on the repo page.

**Comment by askanymark** [comment]
@nabroyan, Are you sure you've typed org name correctly? I had the same exact issue, but then I realized I was inputting my name and not my company's.

**Comment by nabroyan** [comment]
@askanymark I can get public repos of my org with Github API through browser request, so the org name should be correct. 
Did you manage to successfully run the script with the following command?
`github_changelog_generator -u my_company -p private_repo_id -t generated_token`

Is the repository that you're running on private?

**Comment by askanymark** [comment]
@nabroyan Yes, all repos in our organisation are private. However, I do have admin access everywhere, so that might have something to do with it.

**Comment by ferllings** [comment]
Same issue for me

**Comment by woprrr** [comment]
Same problem for my organization :( any solutions ?

**Comment by woprrr** [comment]
The script execute : /Library/Ruby/Gems/2.6.0/gems/octokit-4.18.0/lib/octokit/response/raise_error.rb:16:in `on_complete': **GET https://api.github.com/repos/IAD-INTERNATIONAL/adr/tags?per_page=100:** 404 - Not Found // See: https://developer.github.com/v3/repos/#list-tags (Octokit::NotFound)

In that case like describe in GITHUB API we have any solution :( (With personal repo that work but not with organisation)
And that does be : /org

**Comment by Rafatcb** [comment]
I had the same problem. Solved it by checking "Full control of private repositories" when generating the token:

![image](https://user-images.githubusercontent.com/26308880/108383453-9456cd00-71e8-11eb-8a08-3532b4176e8a.png)
