### ISSUE TITLE
SSL error on Windows with docker

### ISSUE THREAD

**Issue by JBtje** [github-changelog-generator/github-changelog-generator#894]
When I run the following command

```
docker run -it --rm -v "$(pwd):/usr/local/src/your-app" ferrarimarco/github-changelog-generator
  --github-site="https://git.[domain].com"
  --github-api="https://git.[domain].com/api/v3/"
  --token="[Token]"
  --user="[User]"
  --project="[Project]"
```
_As a single line, enters added for readability only._ I get the following error:

```
Traceback (most recent call last):
        43: from /usr/local/bundle/bin/github_changelog_generator:23:in `<main>'
        42: from /usr/local/bundle/bin/github_changelog_generator:23:in `load'
        41: from /usr/local/bundle/gems/github_changelog_generator-1.15.2/bin/github_changelog_generator:5:in `<top (required)>'
        40: from /usr/local/bundle/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator.rb:35:in `run'
        39: from /usr/local/bundle/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/generator/generator.rb:46:in `compound_changelog'
        38: from /usr/local/bundle/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/generator/generator_tags.rb:10:in `fetch_and_filter_tags'
        37: from /usr/local/bundle/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:85:in `get_all_tags'
        36: from /usr/local/bundle/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:399:in `check_github_response'
        35: from /usr/local/bundle/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
        34: from /usr/local/bundle/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
        33: from /usr/local/bundle/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
        32: from /usr/local/bundle/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:400:in `block in check_github_response'
        31: from /usr/local/bundle/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:85:in `block in get_all_tags'
        30: from /usr/local/bundle/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:112:in `github_fetch_tags'
        29: from /usr/local/bundle/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:93:in `calculate_pages'
        28: from /usr/local/bundle/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:399:in `check_github_response'
        27: from /usr/local/bundle/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
        26: from /usr/local/bundle/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
        25: from /usr/local/bundle/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
        24: from /usr/local/bundle/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:400:in `block in check_github_response'
        23: from /usr/local/bundle/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:94:in `block in calculate_pages'
        22: from /usr/local/bundle/gems/octokit-4.18.0/lib/octokit/client/repositories.rb:552:in `tags'
        21: from /usr/local/bundle/gems/octokit-4.18.0/lib/octokit/connection.rb:84:in `paginate'
        20: from /usr/local/bundle/gems/octokit-4.18.0/lib/octokit/connection.rb:156:in `request'
        19: from /usr/local/bundle/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
        18: from /usr/local/bundle/gems/faraday-1.0.1/lib/faraday/connection.rb:198:in `get'
        17: from /usr/local/bundle/gems/faraday-1.0.1/lib/faraday/connection.rb:492:in `run_request'
        16: from /usr/local/bundle/gems/faraday-1.0.1/lib/faraday/rack_builder.rb:153:in `build_response'
        15: from /usr/local/bundle/gems/faraday-http-cache-2.2.0/lib/faraday/http_cache.rb:115:in `call'
        14: from /usr/local/bundle/gems/faraday-http-cache-2.2.0/lib/faraday/http_cache.rb:135:in `call!'
        13: from /usr/local/bundle/gems/faraday-http-cache-2.2.0/lib/faraday/http_cache.rb:187:in `process'
        12: from /usr/local/bundle/gems/faraday-http-cache-2.2.0/lib/faraday/http_cache.rb:283:in `fetch'
        11: from /usr/local/bundle/gems/faraday-1.0.1/lib/faraday/response.rb:11:in `call'
        10: from /usr/local/bundle/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:68:in `call'
         9: from /usr/local/bundle/gems/faraday-1.0.1/lib/faraday/adapter.rb:60:in `connection'
         8: from /usr/local/bundle/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:70:in `block in call'
         7: from /usr/local/bundle/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:128:in `perform_request'
         6: from /usr/local/bundle/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:135:in `request_with_wrapped_block'
         5: from /usr/local/bundle/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:144:in `request_via_get_method'
         4: from /usr/local/lib/ruby/2.6.0/net/http.rb:919:in `start'
         3: from /usr/local/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
         2: from /usr/local/lib/ruby/2.6.0/net/http.rb:996:in `connect'
         1: from /usr/local/lib/ruby/2.6.0/net/protocol.rb:44:in `ssl_socket_connect'
/usr/local/lib/ruby/2.6.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate) (OpenSSL::SSL::SSLError)
        43: from /usr/local/bundle/bin/github_changelog_generator:23:in `<main>'
        42: from /usr/local/bundle/bin/github_changelog_generator:23:in `load'
        41: from /usr/local/bundle/gems/github_changelog_generator-1.15.2/bin/github_changelog_generator:5:in `<top (required)>'
        40: from /usr/local/bundle/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator.rb:35:in `run'
        39: from /usr/local/bundle/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/generator/generator.rb:46:in `compound_changelog'
        38: from /usr/local/bundle/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/generator/generator_tags.rb:10:in `fetch_and_filter_tags'
        37: from /usr/local/bundle/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:85:in `get_all_tags'
        36: from /usr/local/bundle/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:399:in `check_github_response'
        35: from /usr/local/bundle/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
        34: from /usr/local/bundle/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
        33: from /usr/local/bundle/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
        32: from /usr/local/bundle/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:400:in `block in check_github_response'
        31: from /usr/local/bundle/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:85:in `block in get_all_tags'
        30: from /usr/local/bundle/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:112:in `github_fetch_tags'
        29: from /usr/local/bundle/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:93:in `calculate_pages'
        28: from /usr/local/bundle/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:399:in `check_github_response'
        27: from /usr/local/bundle/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
        26: from /usr/local/bundle/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
        25: from /usr/local/bundle/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
        24: from /usr/local/bundle/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:400:in `block in check_github_response'
        23: from /usr/local/bundle/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:94:in `block in calculate_pages'
        22: from /usr/local/bundle/gems/octokit-4.18.0/lib/octokit/client/repositories.rb:552:in `tags'
        21: from /usr/local/bundle/gems/octokit-4.18.0/lib/octokit/connection.rb:84:in `paginate'
        20: from /usr/local/bundle/gems/octokit-4.18.0/lib/octokit/connection.rb:156:in `request'
        19: from /usr/local/bundle/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
        18: from /usr/local/bundle/gems/faraday-1.0.1/lib/faraday/connection.rb:198:in `get'
        17: from /usr/local/bundle/gems/faraday-1.0.1/lib/faraday/connection.rb:492:in `run_request'
        16: from /usr/local/bundle/gems/faraday-1.0.1/lib/faraday/rack_builder.rb:153:in `build_response'
        15: from /usr/local/bundle/gems/faraday-http-cache-2.2.0/lib/faraday/http_cache.rb:115:in `call'
        14: from /usr/local/bundle/gems/faraday-http-cache-2.2.0/lib/faraday/http_cache.rb:135:in `call!'
        13: from /usr/local/bundle/gems/faraday-http-cache-2.2.0/lib/faraday/http_cache.rb:187:in `process'
        12: from /usr/local/bundle/gems/faraday-http-cache-2.2.0/lib/faraday/http_cache.rb:283:in `fetch'
        11: from /usr/local/bundle/gems/faraday-1.0.1/lib/faraday/response.rb:11:in `call'
        10: from /usr/local/bundle/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:68:in `call'
         9: from /usr/local/bundle/gems/faraday-1.0.1/lib/faraday/adapter.rb:60:in `connection'
         8: from /usr/local/bundle/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:70:in `block in call'
         7: from /usr/local/bundle/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:128:in `perform_request'
         6: from /usr/local/bundle/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:135:in `request_with_wrapped_block'
         5: from /usr/local/bundle/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:144:in `request_via_get_method'
         4: from /usr/local/lib/ruby/2.6.0/net/http.rb:919:in `start'
         3: from /usr/local/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
         2: from /usr/local/lib/ruby/2.6.0/net/http.rb:996:in `connect'
         1: from /usr/local/lib/ruby/2.6.0/net/protocol.rb:44:in `ssl_socket_connect'
/usr/local/lib/ruby/2.6.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate) (Faraday::SSLError)
```

The SSL certificate is valid, the server is however not reachable from outside the network. Is there anything I can do to solve this?

**Comment by skywinder** [comment]
Hello. I didn't try to run it with docker. So cant help with this issue.

**Comment by ferrarimarco** [comment]
@JBtje can you try pinning the image version to `ferrarimarco/github-changelog-generator:1.15.2`?

**Comment by baza2099** [comment]
@ferrarimarco getting the same error using the following:  ferrarimarco/github-changelog-generator:1.15.2

**Comment by ferrarimarco** [comment]
Can you open an issue in https://github.com/github-changelog-generator/docker-github-changelog-generator, after trying with the latest release?
