### ISSUE TITLE
uninitialized constant Faraday::Error::ClientError (NameError)

### ISSUE THREAD

**Issue by vanniktech** [github-changelog-generator/github-changelog-generator#896]
```
Traceback (most recent call last):
	15: from /usr/local/bin/github_changelog_generator:23:in `<main>'
	14: from /usr/local/bin/github_changelog_generator:23:in `load'
	13: from /Library/Ruby/Gems/2.6.0/gems/github_changelog_generator-1.15.2/bin/github_changelog_generator:4:in `<top (required)>'
	12: from /Library/Ruby/Gems/2.6.0/gems/github_changelog_generator-1.15.2/bin/github_changelog_generator:4:in `require_relative'
	11: from /Library/Ruby/Gems/2.6.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator.rb:4:in `<top (required)>'
	10: from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 9: from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 8: from /Library/Ruby/Gems/2.6.0/gems/octokit-4.14.0/lib/octokit.rb:4:in `<top (required)>'
	 7: from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 6: from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 5: from /Library/Ruby/Gems/2.6.0/gems/octokit-4.14.0/lib/octokit/default.rb:1:in `<top (required)>'
	 4: from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 3: from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 2: from /Library/Ruby/Gems/2.6.0/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:9:in `<top (required)>'
	 1: from /Library/Ruby/Gems/2.6.0/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:11:in `<module:Octokit>'
/Library/Ruby/Gems/2.6.0/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:14:in `<module:Middleware>': uninitialized constant Faraday::Error::ClientError (NameError)
Did you mean?  Faraday::ClientError
```

Would it be possible to adjust the breaking change?

**Comment by skywinder** [comment]
Which version do you use?

**Comment by vanniktech** [comment]
```
➜  ~ git:(master) ✗ gem list github_changelog_generator

*** LOCAL GEMS ***

github_changelog_generator (1.15.2)
```

**Comment by vanniktech** [comment]
This is still an issue for me:

```
➜  lint-rules git:(master) ✗ sudo gem install github_changelog_generator -n /usr/local/bin
Fetching github_changelog_generator-1.15.2.gem
Fetching faraday-1.3.0.gem
Successfully installed faraday-1.3.0
Successfully installed github_changelog_generator-1.15.2
Parsing documentation for faraday-1.3.0
Installing ri documentation for faraday-1.3.0
Parsing documentation for github_changelog_generator-1.15.2
Installing ri documentation for github_changelog_generator-1.15.2
Done installing documentation for faraday, github_changelog_generator after 2 seconds
2 gems installed
➜  lint-rules git:(master) github_changelog_generator --user vanniktech --project lint-rules
Traceback (most recent call last):
	15: from /usr/local/bin/github_changelog_generator:23:in `<main>'
	14: from /usr/local/bin/github_changelog_generator:23:in `load'
	13: from /Library/Ruby/Gems/2.6.0/gems/github_changelog_generator-1.15.2/bin/github_changelog_generator:4:in `<top (required)>'
	12: from /Library/Ruby/Gems/2.6.0/gems/github_changelog_generator-1.15.2/bin/github_changelog_generator:4:in `require_relative'
	11: from /Library/Ruby/Gems/2.6.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator.rb:4:in `<top (required)>'
	10: from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 9: from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 8: from /Library/Ruby/Gems/2.6.0/gems/octokit-4.14.0/lib/octokit.rb:4:in `<top (required)>'
	 7: from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 6: from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 5: from /Library/Ruby/Gems/2.6.0/gems/octokit-4.14.0/lib/octokit/default.rb:1:in `<top (required)>'
	 4: from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 3: from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 2: from /Library/Ruby/Gems/2.6.0/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:9:in `<top (required)>'
	 1: from /Library/Ruby/Gems/2.6.0/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:11:in `<module:Octokit>'
/Library/Ruby/Gems/2.6.0/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:14:in `<module:Middleware>': uninitialized constant Faraday::Error::ClientError (NameError)
Did you mean?  Faraday::ClientError
```

**Comment by olleolleolle** [comment]
So, 

4.14.0 octokit derives from an older Faraday error class.
https://github.com/octokit/octokit.rb/blob/v4.14.0/lib/octokit/middleware/follow_redirects.rb

4.15.0 and onwards, octokit uses the expected error class.

**Comment by olleolleolle** [comment]
The repair was done in Octokit, by this commit.

https://github.com/octokit/octokit.rb/commit/3e9054bb2019a5c07fe62ecda01cf09d8a60dd44

Closing 👋 !
