### ISSUE TITLE
500 - Server Error: Sorry, this diff is taking too long to generate.

### ISSUE THREAD

**Issue by waltermaldonado** [github-changelog-generator/github-changelog-generator#920]
I think large diffs must be handled, this is preventing me from generating the changelogs:

```
Traceback (most recent call last):
        22: from /usr/local/bundle/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:323:in `block (3 levels) in fetch_tag_shas_async'
        21: from /usr/local/bundle/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:257:in `fetch_compare'
        20: from /usr/local/bundle/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:399:in `check_github_response'
        19: from /usr/local/bundle/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
        18: from /usr/local/bundle/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
        17: from /usr/local/bundle/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
        16: from /usr/local/bundle/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:400:in `block in check_github_response'
        15: from /usr/local/bundle/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:257:in `block in fetch_compare'
        14: from /usr/local/bundle/gems/octokit-4.18.0/lib/octokit/client/commits.rb:198:in `compare'
        13: from /usr/local/bundle/gems/octokit-4.18.0/lib/octokit/connection.rb:19:in `get'
        12: from /usr/local/bundle/gems/octokit-4.18.0/lib/octokit/connection.rb:156:in `request'
        11: from /usr/local/bundle/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
        10: from /usr/local/bundle/gems/faraday-1.0.1/lib/faraday/connection.rb:198:in `get'
         9: from /usr/local/bundle/gems/faraday-1.0.1/lib/faraday/connection.rb:492:in `run_request'
         8: from /usr/local/bundle/gems/faraday-1.0.1/lib/faraday/rack_builder.rb:153:in `build_response'
         7: from /usr/local/bundle/gems/faraday-http-cache-2.2.0/lib/faraday/http_cache.rb:115:in `call'
         6: from /usr/local/bundle/gems/faraday-http-cache-2.2.0/lib/faraday/http_cache.rb:135:in `call!'
         5: from /usr/local/bundle/gems/faraday-http-cache-2.2.0/lib/faraday/http_cache.rb:187:in `process'
         4: from /usr/local/bundle/gems/faraday-http-cache-2.2.0/lib/faraday/http_cache.rb:283:in `fetch'
         3: from /usr/local/bundle/gems/faraday-1.0.1/lib/faraday/response.rb:11:in `call'
         2: from /usr/local/bundle/gems/faraday-1.0.1/lib/faraday/response.rb:65:in `on_complete'
         1: from /usr/local/bundle/gems/faraday-1.0.1/lib/faraday/response.rb:12:in `block in call'
/usr/local/bundle/gems/octokit-4.18.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://<host>/api/v3/repos/<user>/<repo>/compare/506be01d73fc904ed994f7e880f32b4e8c7478f5...1.10.1: 500 - Server Error: Sorry, this diff is taking too long to generate. (Octokit::InternalServerError)
Error summary:
  resource: Comparison
  field: diff
  code: not_available // See: https://docs.github.com/enterprise/2.22/rest/reference/repos#compare-two-commits
```

Any workarounds for now?

**Comment by skywinder** [comment]
Which commands arguments do you use?

**Comment by waltermaldonado** [comment]
Default configs with
```
github_changelog_generator -u MyUser -p MyProj --github-site="https://github.yoursite.com" --github-api="https://github.yoursite.com/api/v3/"
```

It works for some repos but for others it doesn't, specially ones with large commits.
