### ISSUE TITLE
No merge sha found for PR * via the GitHub API (StandardError)

### ISSUE THREAD

**Issue by schinj** [github-changelog-generator/github-changelog-generator#927]
Hi,

Thanks for this amazing library.
I am facing the below issue on running the change-log generator command:

Logs:
...
Found 95 tags
Fetching tags dates: 95/95
Sorting tags...
Received issues: 512
Pull Request count: 504
Filtered pull requests: 408
Filtered issues: 8
Fetching events for issues and PR: 416
Fetching closed dates for issues: 416/416
Fetching SHAs for tags: 95
*/vendor/bundle/ruby/2.6.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/generator/generator_fetcher.rb:88:in `block in associate_tagged_prs': No merge sha found for PR 57 via the GitHub API (StandardError)
	from */vendor/bundle/ruby/2.6.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/generator/generator_fetcher.rb:70:in `reject'
	from */vendor/bundle/ruby/2.6.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/generator/generator_fetcher.rb:70:in `associate_tagged_prs'
	from */vendor/bundle/ruby/2.6.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/generator/generator_fetcher.rb:50:in `add_first_occurring_tag_to_prs'
	from */vendor/bundle/ruby/2.6.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/generator/generator.rb:151:in `fetch_issues_and_pr'
	from */vendor/bundle/ruby/2.6.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/generator/generator.rb:47:in `compound_changelog'
	from */vendor/bundle/ruby/2.6.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator.rb:35:in `run'
	from */vendor/bundle/ruby/2.6.0/gems/github_changelog_generator-1.15.2/bin/github_changelog_generator:5:in `<top (required)>'
	from */vendor/bundle/ruby/2.6.0/bin/github_changelog_generator:23:in `load'
	from */vendor/bundle/ruby/2.6.0/bin/github_changelog_generator:23:in `<main>'
Warning: PR 57 merge commit was not found in the release branch or tagged git history and no rebased SHA comment was found

Could you please help me in debugging this issue?

**Comment by ameir** [comment]
I just tested out this project as well and had this same issue. FWIW, I commented out that line and it completed successfully, although I'm sure it's missing some data.

**Comment by schinj** [comment]
@ameir But are you able to get the expected changelog set?

**Comment by rposborne** [comment]
Seeing this as well on the https://github.com/countries/countries repo for PR 1.

**Comment by lukebakken** [comment]
FWIW, I ran into this while trying out this project on Pika (https://github.com/pika/pika/).

Rather than raising the error, I had the message printed via `STDERR.puts`. In the generated CHANGELOG.md, there were a couple invalid entries but they were easily removed.
