### ISSUE TITLE
Octokit::NotFound error

### ISSUE THREAD

**Issue by morevnaproject** [github-changelog-generator/github-changelog-generator#931]
Hi! I am facing the below issue on running the `github_changelog_generator` command:

```
$ github_changelog_generator -u synfig -p synfig
Using these options:
:date_format=>"%Y-%m-%d"
:output=>"CHANGELOG.md"
:base=>"HISTORY.md"
:issues=>true
:add_issues_wo_labels=>true
:add_pr_wo_labels=>true
:pulls=>true
:filter_issues_by_milestone=>true
:author=>true
:unreleased=>true
:unreleased_label=>"Unreleased"
:compare_link=>true
:exclude_labels=>["duplicate", "question", "invalid", "wontfix", "Duplicate", "Question", "Invalid", "Wontfix", "Meta: Exclude From Changelog"]
:summary_labels=>["Release summary", "release-summary", "Summary", "summary"]
:breaking_labels=>["backwards-incompatible", "Backwards incompatible", "breaking"]
:enhancement_labels=>["enhancement", "Enhancement", "Type: Enhancement"]
:bug_labels=>["bug", "Bug", "Type: Bug"]
:deprecated_labels=>["deprecated", "Deprecated", "Type: Deprecated"]
:removed_labels=>["removed", "Removed", "Type: Removed"]
:security_labels=>["security", "Security", "Type: Security"]
:configure_sections=>{}
:add_sections=>{}
:issue_line_labels=>[]
:max_issues=>nil
:simple_list=>false
:ssl_ca_file=>nil
:verbose=>true
:header=>"# Changelog"
:merge_prefix=>"**Merged pull requests:**"
:issue_prefix=>"**Closed issues:**"
:summary_prefix=>""
:breaking_prefix=>"**Breaking changes:**"
:enhancement_prefix=>"**Implemented enhancements:**"
:bug_prefix=>"**Fixed bugs:**"
:deprecated_prefix=>"**Deprecated:**"
:removed_prefix=>"**Removed:**"
:security_prefix=>"**Security fixes:**"
:http_cache=>true
:require=>[]
:user=>"synfig"
:project=>"synfig"
:token=>"No token used"

Found 95 tags                                                          
Fetching tags dates: 95/95
Sorting tags...
Received issues: 1503                                                  
Pull Request count: 884                                                
Filtered pull requests: 713
Filtered issues: 615
Fetching events for issues and PR: 1328                                
Warning: Can't fetch commit b112939ece57758387836c4dafc5fb856ee88bf8. It is probably referenced from another repo.
Fetching closed dates for issues: 1328/1328
#<Thread:0x000055c7489f5578@/var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:321 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	22: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:323:in `block (3 levels) in fetch_tag_shas_async'
	21: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:257:in `fetch_compare'
	20: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:399:in `check_github_response'
	19: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
	18: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
	17: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
	16: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:400:in `block in check_github_response'
	15: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:257:in `block in fetch_compare'
	14: from /var/lib/gems/2.5.0/gems/octokit-4.20.0/lib/octokit/client/commits.rb:198:in `compare'
	13: from /var/lib/gems/2.5.0/gems/octokit-4.20.0/lib/octokit/connection.rb:19:in `get'
	12: from /var/lib/gems/2.5.0/gems/octokit-4.20.0/lib/octokit/connection.rb:156:in `request'
	11: from /var/lib/gems/2.5.0/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
	10: from /var/lib/gems/2.5.0/gems/faraday-1.3.0/lib/faraday/connection.rb:198:in `get'
	 9: from /var/lib/gems/2.5.0/gems/faraday-1.3.0/lib/faraday/connection.rb:492:in `run_request'
	 8: from /var/lib/gems/2.5.0/gems/faraday-1.3.0/lib/faraday/rack_builder.rb:154:in `build_response'
	 7: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.2.0/lib/faraday/http_cache.rb:115:in `call'
	 6: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.2.0/lib/faraday/http_cache.rb:135:in `call!'
	 5: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.2.0/lib/faraday/http_cache.rb:187:in `process'
	 4: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.2.0/lib/faraday/http_cache.rb:283:in `fetch'
	 3: from /var/lib/gems/2.5.0/gems/faraday-1.3.0/lib/faraday/middleware.rb:18:in `call'
	 2: from /var/lib/gems/2.5.0/gems/faraday-1.3.0/lib/faraday/response.rb:59:in `on_complete'
	 1: from /var/lib/gems/2.5.0/gems/faraday-1.3.0/lib/faraday/middleware.rb:19:in `block in call'
/var/lib/gems/2.5.0/gems/octokit-4.20.0/lib/octokit/response/raise_error.rb:14:in `on_complete': GET https://api.github.com/repos/synfig/synfig/compare/7f4273493da74d7d5746a65551e20c7786d0f155...bug: 404 - Not Found // See: https://docs.github.com/rest/reference/repos#compare-two-commits (Octokit::NotFound)
Traceback (most recent call last):
	22: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:323:in `block (3 levels) in fetch_tag_shas_async'
	21: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:257:in `fetch_compare'
	20: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:399:in `check_github_response'
	19: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
	18: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
	17: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
	16: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:400:in `block in check_github_response'
	15: from /var/lib/gems/2.5.0/gems/github_changelog_generator-1.15.2/lib/github_changelog_generator/octo_fetcher.rb:257:in `block in fetch_compare'
	14: from /var/lib/gems/2.5.0/gems/octokit-4.20.0/lib/octokit/client/commits.rb:198:in `compare'
	13: from /var/lib/gems/2.5.0/gems/octokit-4.20.0/lib/octokit/connection.rb:19:in `get'
	12: from /var/lib/gems/2.5.0/gems/octokit-4.20.0/lib/octokit/connection.rb:156:in `request'
	11: from /var/lib/gems/2.5.0/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
	10: from /var/lib/gems/2.5.0/gems/faraday-1.3.0/lib/faraday/connection.rb:198:in `get'
	 9: from /var/lib/gems/2.5.0/gems/faraday-1.3.0/lib/faraday/connection.rb:492:in `run_request'
	 8: from /var/lib/gems/2.5.0/gems/faraday-1.3.0/lib/faraday/rack_builder.rb:154:in `build_response'
	 7: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.2.0/lib/faraday/http_cache.rb:115:in `call'
	 6: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.2.0/lib/faraday/http_cache.rb:135:in `call!'
	 5: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.2.0/lib/faraday/http_cache.rb:187:in `process'
	 4: from /var/lib/gems/2.5.0/gems/faraday-http-cache-2.2.0/lib/faraday/http_cache.rb:283:in `fetch'
	 3: from /var/lib/gems/2.5.0/gems/faraday-1.3.0/lib/faraday/middleware.rb:18:in `call'
	 2: from /var/lib/gems/2.5.0/gems/faraday-1.3.0/lib/faraday/response.rb:59:in `on_complete'
	 1: from /var/lib/gems/2.5.0/gems/faraday-1.3.0/lib/faraday/middleware.rb:19:in `block in call'
/var/lib/gems/2.5.0/gems/octokit-4.20.0/lib/octokit/response/raise_error.rb:14:in `on_complete': GET https://api.github.com/repos/synfig/synfig/compare/7f4273493da74d7d5746a65551e20c7786d0f155...bug: 404 - Not Found // See: https://docs.github.com/rest/reference/repos#compare-two-commits (Octokit::NotFound)
```

Any help is appreciated! ^__^

**Comment by alessioscalici** [comment]
Me too!
