### ISSUE TITLE
Getting an error: ` 'list_issues': wrong number of arguments (given 3, expected 0..2) (ArgumentError)`

### ISSUE THREAD

**Issue by kigster** [github-changelog-generator/github-changelog-generator#952]
**Describe the bug**

Running it on my private private repo, **which does not have any issues logged**, but does have a bunch of tags,  although the same error happens even after I created a dummy issue.
 
```bash
$  cat .github_changelog_generator
since-tag=v0.2.0
$ github_changelog_generator --project YYYY --user XXXXX -t ZZZZZ
/Users/kig/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/octokit-4.20.0/lib/octokit/client/issues.rb:30:in 'list_issues': wrong number of arguments (given 3, expected 0..2) (ArgumentError)
	from /Users/kig/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/github_changelog_generator-1.16.1/lib/github_changelog_generator/octo_fetcher.rb:415:in 'block in iterate_pages'
	from /Users/kig/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/retriable-3.1.2/lib/retriable.rb:61:in 'block in retriable'
	from /Users/kig/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/retriable-3.1.2/lib/retriable.rb:56:in 'times'
	from /Users/kig/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/retriable-3.1.2/lib/retriable.rb:56:in 'retriable'
	from /Users/kig/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/github_changelog_generator-1.16.1/lib/github_changelog_generator/octo_fetcher.rb:446:in check_github_response'
	from /Users/kig/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/github_changelog_generator-1.16.1/lib/github_changelog_generator/octo_fetcher.rb:415:in 'iterate_pages'
	from /Users/kig/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/github_changelog_generator-1.16.1/lib/github_changelog_generator/octo_fetcher.rb:164:in 'fetch_closed_issues_and_pr'
	from /Users/kig/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/github_changelog_generator-1.16.1/lib/github_changelog_generator/generator/generator.rb:144:in 'fetch_issues_and_pr'
	from /Users/kig/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/github_changelog_generator-1.16.1/lib/github_changelog_generator/generator/generator.rb:55:in 'block in compound_changelog'
	from /Users/kig/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/async-1.28.9/lib/async/task.rb:265:in 'block in make_fiber'
```

### To Reproduce

Unfortunately, this is a private repo.

Ruby versions tried:

 * 3.0.0

Gem version tried:

 * 1.16.1

**Comment by olleolleolle** [comment]
The method called is here:

https://github.com/github-changelog-generator/github-changelog-generator/blob/master/lib/github_changelog_generator/octo_fetcher.rb#L415

**Comment by marcoroth** [comment]
If you need a public repo to reproduce the issue: We ran into the same issue in [`stimulus_reflex`](https://github.com/hopsoft/stimulus_reflex).

Downgrading `github_changelog_generator` to `v1.15.2` seems to resolve the issue for us.

Locally I can reproduce the `ArgumentError` with this using Ruby 3.0.0 and 1.16.1:

```bash
github_changelog_generator -u hopsoft -p stimulus_reflex --exclude-labels duplicate,question,invalid,wontfix,nodoc --token {token}
```
